[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.build]
cmds = [
  "npm install --no-optional",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"